### ISSUE TITLE
aliases aren't CLI firendly

### ISSUE THREAD

**Issue by bnb** [pkgjs/nv#23]
I'm currently working on a CLI that's building off of this work, and I've found that the aliases are relatively unfriendly to CLIs. I've never seen a Node.js native command line tool that uses underscores, and am finding myself having to alias them which provides a less cohesive experience than I'd like. 

I'd like to request that more CLI-friendly aliasing be introduced for the lts variants.

**Comment by wesleytodd** [comment]
Those aliases were defined by the package maintenance working group, not this tool. I do agree that the aliases keys are not super friendly, maybe we could change how they are defined in the spec and then release v2?

**Comment by bnb** [comment]
+1 I'm happy to change how they're defined in the spec and release an update.

**Comment by shadowspawn** [comment]
Are you talking about changing the node namespace aliases in https://github.com/nodejs/package-maintenance/blob/main/docs/PACKAGE-SUPPORT.md ?

They are being used in `package-support.json` files and in code outside the node organisation (e.g. https://github.com/tj/n/blob/392f9ab7d8434f9a73386a6cea055fafb7b37f86/bin/n#L305). Changing the node namespace aliases for a little more CLI friendliness seems expensive.

Perhaps you are weighing all of that, or perhaps it is some other definition you are talking about. I wanted to clarify because it seemed very casually discussed. 🤭

**Comment by bnb** [comment]
> They are being used in package-support.json files and in code outside the node organisation (e.g. https://github.com/tj/n/blob/392f9ab7d8434f9a73386a6cea055fafb7b37f86/bin/n#L305). Changing the node namespace aliases for a little more CLI friendliness seems expensive.

I am talking about those. I'll be frank, I don't think that they're a good API and should not be used in end-user APIs that module maintainers should be using. If changing them is not something that is possible, I'll strongly recommend we abandon using them.

**Comment by bnb** [comment]
IMO yes. Having non-CLI-friendly names is borderline a non-starter.

**Comment by wesleytodd** [comment]
Going to close this and point to your PR in the PMWG: https://github.com/nodejs/package-maintenance/pull/581

Once that is resolved I can update the package and release a new major with the new aliases.
