### ISSUE TITLE
supported vs maintained

### ISSUE THREAD

**Issue by shadowspawn** [pkgjs/nv#7]
As noted in the README, there isn't a canonical reference yet, but raising an apparent terminology variation in the current draft documents. (This may have been resolved in a discussion I didn't find.)

`nv` supports an alias for `maintained`, but https://github.com/nodejs/package-maintenance/blob/master/docs/drafts/PACKAGE-SUPPORT.md#node-name-space lists a target alias of `supported`

**Comment by wesleytodd** [comment]
@odejs/package-maintenance Anyone want to take a look at addressing this?

I also think we should consider moving [what is documented in this issue](https://github.com/nodejs/package-maintenance/issues/236) into a document of it's own then reference it from the package support proposal.  I say this because I think we should move faster on the standardized grammar than the support work (which has been stalled lately).  Thoughts?

**Comment by wesleytodd** [comment]
Ok, I wonder why the team tag does not work over here.  Since that does not work, I am going to move this conversation over to the working group repo as that is where this conversation probably belongs anyway.

**Comment by wesleytodd** [comment]
Closed in favor of discussion in PM WG.
